/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gato;

import javax.swing.JOptionPane;

/**
 *
 * @author Fabián
 */



public class juego extends javax.swing.JFrame {

    String ganador = "Fin del juego, ganador : ";
    String empate = "Fin del juego, no hay ganador";
    
    /**
     * Creates new form juego
     */
    int vict = 0;
    int vict2 = 0;
    String jugador1 = "X";
    String jugador2 = "O";
    int cont = 0;
    int cont1 = 0;
    int cont2 = 0;
    int cont3 = 0;
    int cont4 = 0;
    int cont5 = 0;
    int cont6 = 0;
    int cont7 = 0;
    int cont8 = 0;
    int cont9 = 0;

    String b1 = " ";
    String b2 = "  ";
    String b3 = "   ";
    String b4 = "    ";
    String b5 = "     ";
    String b6 = "      ";
    String b7 = "       ";
    String b8 = "        ";
    String b9 = "         ";
    
    

    public juego() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Gato");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText(" ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("  ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("   ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("    ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("     ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("      ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("       ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("        ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("         ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setText("Jugador 1:");

        jLabel2.setText("0");

        jLabel3.setText("Jugador 2:");

        jLabel4.setText("0");

        jLabel5.setText("Victorias:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int ver = 0;
        cont1++;
        if (cont1 > 1) {
            JOptionPane.showMessageDialog(null, "Casillero ocupado");
        } else {
            cont++;
            if (cont % 2 == 0) {
                jButton1.setText(jugador1);
            } else {
                jButton1.setText(jugador2);
            }
            String g1 = jButton1.getText();
            String g2 = jButton2.getText();
            String g3 = jButton3.getText();
            String g4 = jButton4.getText();
            String g5 = jButton5.getText();
            String g6 = jButton6.getText();
            String g7 = jButton7.getText();
            String g8 = jButton8.getText();
            String g9 = jButton9.getText();

            if (g1.equals(g2) && g2.equals(g3) || g1.equals(g4) && g4.equals(g7) || g1.equals(g5) && g5.equals(g9) || g7.equals(g8) && g8.equals(g9) || g3.equals(g6) && g6.equals(g9) || g4.equals(g5) && g5.equals(g6) || g2.equals(g5) && g5.equals(g8) || g3.equals(g5) && g5.equals(g7)) {
                if (cont % 2 == 0) {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador1 + "'");
                    vict++;
                    String vict1 = Integer.toString(vict);
                    jLabel2.setText(vict1);
                } else {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador2 + "'");
                    vict2++;
                    String vict1 = Integer.toString(vict2);
                    jLabel4.setText(vict1);
                }
                

                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
                ver=1;
            }
            if (g1 != b1 && g2 != b2 && g3 != b3 && g4 != b4 && g5 != b5 && g6 != b6 && g7 != b7 && g8 != b8 && g9 != b9) {
                if(ver==0){
                JOptionPane.showMessageDialog(null, empate);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

int ver = 0;
        cont4++;
        if (cont4 > 1) {
            JOptionPane.showMessageDialog(null, "Casillero ocupado");
        } else {
            cont++;
            if (cont % 2 == 0) {
                jButton4.setText(jugador1);
            } else {
                jButton4.setText(jugador2);
            }
            String g1 = jButton1.getText();
            String g2 = jButton2.getText();
            String g3 = jButton3.getText();
            String g4 = jButton4.getText();
            String g5 = jButton5.getText();
            String g6 = jButton6.getText();
            String g7 = jButton7.getText();
            String g8 = jButton8.getText();
            String g9 = jButton9.getText();

            if (g1.equals(g2) && g2.equals(g3) || g1.equals(g4) && g4.equals(g7) || g1.equals(g5) && g5.equals(g9) || g7.equals(g8) && g8.equals(g9) || g3.equals(g6) && g6.equals(g9) || g4.equals(g5) && g5.equals(g6) || g2.equals(g5) && g5.equals(g8) || g3.equals(g5) && g5.equals(g7)) {
                if (cont % 2 == 0) {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador1 + "'");
                    vict++;
                    String vict1 = Integer.toString(vict);
                    jLabel2.setText(vict1);
                } else {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador2 + "'");
                    vict2++;
                    String vict1 = Integer.toString(vict2);
                    jLabel4.setText(vict1);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
                ver=1;
            }
            if (g1 != b1 && g2 != b2 && g3 != b3 && g4 != b4 && g5 != b5 && g6 != b6 && g7 != b7 && g8 != b8 && g9 != b9) {
                if(ver==0){
                JOptionPane.showMessageDialog(null, empate);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

int ver = 0;
        cont7++;
        if (cont7 > 1) {
            JOptionPane.showMessageDialog(null, "Casillero ocupado");
        } else {
            cont++;
            if (cont % 2 == 0) {
                jButton7.setText(jugador1);
            } else {
                jButton7.setText(jugador2);
            }
            String g1 = jButton1.getText();
            String g2 = jButton2.getText();
            String g3 = jButton3.getText();
            String g4 = jButton4.getText();
            String g5 = jButton5.getText();
            String g6 = jButton6.getText();
            String g7 = jButton7.getText();
            String g8 = jButton8.getText();
            String g9 = jButton9.getText();

            if (g1.equals(g2) && g2.equals(g3) || g1.equals(g4) && g4.equals(g7) || g1.equals(g5) && g5.equals(g9) || g7.equals(g8) && g8.equals(g9) || g3.equals(g6) && g6.equals(g9) || g4.equals(g5) && g5.equals(g6) || g2.equals(g5) && g5.equals(g8) || g3.equals(g5) && g5.equals(g7)) {
                if (cont % 2 == 0) {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador1 + "'");
                    vict++;
                    String vict1 = Integer.toString(vict);
                    jLabel2.setText(vict1);
                } else {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador2 + "'");
                    vict2++;
                    String vict1 = Integer.toString(vict2);
                    jLabel4.setText(vict1);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
                ver=1;
            }
            if (g1 != b1 && g2 != b2 && g3 != b3 && g4 != b4 && g5 != b5 && g6 != b6 && g7 != b7 && g8 != b8 && g9 != b9) {
                if(ver==0){
                JOptionPane.showMessageDialog(null, empate);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

int ver = 0;
        cont2++;
        if (cont2 > 1) {
            JOptionPane.showMessageDialog(null, "Casillero ocupado");
        } else {
            cont++;
            if (cont % 2 == 0) {
                jButton2.setText(jugador1);
            } else {
                jButton2.setText(jugador2);
            }
            String g1 = jButton1.getText();
            String g2 = jButton2.getText();
            String g3 = jButton3.getText();
            String g4 = jButton4.getText();
            String g5 = jButton5.getText();
            String g6 = jButton6.getText();
            String g7 = jButton7.getText();
            String g8 = jButton8.getText();
            String g9 = jButton9.getText();

            if (g1.equals(g2) && g2.equals(g3) || g1.equals(g4) && g4.equals(g7) || g1.equals(g5) && g5.equals(g9) || g7.equals(g8) && g8.equals(g9) || g3.equals(g6) && g6.equals(g9) || g4.equals(g5) && g5.equals(g6) || g2.equals(g5) && g5.equals(g8) || g3.equals(g5) && g5.equals(g7)) {
                if (cont % 2 == 0) {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador1 + "'");
                    vict++;
                    String vict1 = Integer.toString(vict);
                    jLabel2.setText(vict1);
                } else {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador2 + "'");
                    vict2++;
                    String vict1 = Integer.toString(vict2);
                    jLabel4.setText(vict1);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
                ver=1;
            }
            if (g1 != b1 && g2 != b2 && g3 != b3 && g4 != b4 && g5 != b5 && g6 != b6 && g7 != b7 && g8 != b8 && g9 != b9) {
                if(ver==0){
                JOptionPane.showMessageDialog(null, empate);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

int ver = 0;
        cont5++;
        if (cont5 > 1) {
            JOptionPane.showMessageDialog(null, "Casillero ocupado");
        } else {
            cont++;
            if (cont % 2 == 0) {
                jButton5.setText(jugador1);
            } else {
                jButton5.setText(jugador2);
            }
            String g1 = jButton1.getText();
            String g2 = jButton2.getText();
            String g3 = jButton3.getText();
            String g4 = jButton4.getText();
            String g5 = jButton5.getText();
            String g6 = jButton6.getText();
            String g7 = jButton7.getText();
            String g8 = jButton8.getText();
            String g9 = jButton9.getText();

            if (g1.equals(g2) && g2.equals(g3) || g1.equals(g4) && g4.equals(g7) || g1.equals(g5) && g5.equals(g9) || g7.equals(g8) && g8.equals(g9) || g3.equals(g6) && g6.equals(g9) || g4.equals(g5) && g5.equals(g6) || g2.equals(g5) && g5.equals(g8) || g3.equals(g5) && g5.equals(g7)) {
                if (cont % 2 == 0) {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador1 + "'");
                    vict++;
                    String vict1 = Integer.toString(vict);
                    jLabel2.setText(vict1);
                } else {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador2 + "'");
                    vict2++;
                    String vict1 = Integer.toString(vict2);
                    jLabel4.setText(vict1);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
                ver=1;
            }
            if (g1 != b1 && g2 != b2 && g3 != b3 && g4 != b4 && g5 != b5 && g6 != b6 && g7 != b7 && g8 != b8 && g9 != b9) {
                if(ver==0){
                JOptionPane.showMessageDialog(null, empate);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

int ver = 0;
        cont8++;
        if (cont8 > 1) {
            JOptionPane.showMessageDialog(null, "Casillero ocupado");
        } else {
            cont++;
            if (cont % 2 == 0) {
                jButton8.setText(jugador1);
            } else {
                jButton8.setText(jugador2);
            }
            String g1 = jButton1.getText();
            String g2 = jButton2.getText();
            String g3 = jButton3.getText();
            String g4 = jButton4.getText();
            String g5 = jButton5.getText();
            String g6 = jButton6.getText();
            String g7 = jButton7.getText();
            String g8 = jButton8.getText();
            String g9 = jButton9.getText();

            if (g1.equals(g2) && g2.equals(g3) || g1.equals(g4) && g4.equals(g7) || g1.equals(g5) && g5.equals(g9) || g7.equals(g8) && g8.equals(g9) || g3.equals(g6) && g6.equals(g9) || g4.equals(g5) && g5.equals(g6) || g2.equals(g5) && g5.equals(g8) || g3.equals(g5) && g5.equals(g7)) {
                if (cont % 2 == 0) {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador1 + "'");
                    vict++;
                    String vict1 = Integer.toString(vict);
                    jLabel2.setText(vict1);
                } else {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador2 + "'");
                    vict2++;
                    String vict1 = Integer.toString(vict2);
                    jLabel4.setText(vict1);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
                ver=1;
            }
            if (g1 != b1 && g2 != b2 && g3 != b3 && g4 != b4 && g5 != b5 && g6 != b6 && g7 != b7 && g8 != b8 && g9 != b9) {
                if(ver==0){
                JOptionPane.showMessageDialog(null, empate);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

int ver = 0;
        cont3++;
        if (cont3 > 1) {
            JOptionPane.showMessageDialog(null, "Casillero ocupado");
        } else {
            cont++;
            if (cont % 2 == 0) {
                jButton3.setText(jugador1);
            } else {
                jButton3.setText(jugador2);
            }
            String g1 = jButton1.getText();
            String g2 = jButton2.getText();
            String g3 = jButton3.getText();
            String g4 = jButton4.getText();
            String g5 = jButton5.getText();
            String g6 = jButton6.getText();
            String g7 = jButton7.getText();
            String g8 = jButton8.getText();
            String g9 = jButton9.getText();

            if (g1.equals(g2) && g2.equals(g3) || g1.equals(g4) && g4.equals(g7) || g1.equals(g5) && g5.equals(g9) || g7.equals(g8) && g8.equals(g9) || g3.equals(g6) && g6.equals(g9) || g4.equals(g5) && g5.equals(g6) || g2.equals(g5) && g5.equals(g8) || g3.equals(g5) && g5.equals(g7)) {
                if (cont % 2 == 0) {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador1 + "'");
                    vict++;
                    String vict1 = Integer.toString(vict);
                    jLabel2.setText(vict1);
                } else {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador2 + "'");
                    vict2++;
                    String vict1 = Integer.toString(vict2);
                    jLabel4.setText(vict1);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
                ver=1;
            }
            if (g1 != b1 && g2 != b2 && g3 != b3 && g4 != b4 && g5 != b5 && g6 != b6 && g7 != b7 && g8 != b8 && g9 != b9) {
                if(ver==0){
                JOptionPane.showMessageDialog(null, empate);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

int ver = 0;
        cont6++;
        if (cont6 > 1) {
            JOptionPane.showMessageDialog(null, "Casillero ocupado");
        } else {
            cont++;
            if (cont % 2 == 0) {
                jButton6.setText(jugador1);
            } else {
                jButton6.setText(jugador2);
            }
            String g1 = jButton1.getText();
            String g2 = jButton2.getText();
            String g3 = jButton3.getText();
            String g4 = jButton4.getText();
            String g5 = jButton5.getText();
            String g6 = jButton6.getText();
            String g7 = jButton7.getText();
            String g8 = jButton8.getText();
            String g9 = jButton9.getText();

            if (g1.equals(g2) && g2.equals(g3) || g1.equals(g4) && g4.equals(g7) || g1.equals(g5) && g5.equals(g9) || g7.equals(g8) && g8.equals(g9) || g3.equals(g6) && g6.equals(g9) || g4.equals(g5) && g5.equals(g6) || g2.equals(g5) && g5.equals(g8) || g3.equals(g5) && g5.equals(g7)) {
                if (cont % 2 == 0) {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador1 + "'");
                    vict++;
                    String vict1 = Integer.toString(vict);
                    jLabel2.setText(vict1);
                    
                } else {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador2 + "'");
                    vict2++;
                    String vict1 = Integer.toString(vict2);
                    jLabel4.setText(vict1);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
                ver=1;
            }
            if (g1 != b1 && g2 != b2 && g3 != b3 && g4 != b4 && g5 != b5 && g6 != b6 && g7 != b7 && g8 != b8 && g9 != b9) {
                if(ver==0){
                JOptionPane.showMessageDialog(null, empate);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
                
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

int ver = 0;
        cont9++;
        if (cont9 > 1) {
            JOptionPane.showMessageDialog(null, "Casillero ocupado");
        } else {
            cont++;
            if (cont % 2 == 0) {
                jButton9.setText(jugador1);
            } else {
                jButton9.setText(jugador2);
            }
            String g1 = jButton1.getText();
            String g2 = jButton2.getText();
            String g3 = jButton3.getText();
            String g4 = jButton4.getText();
            String g5 = jButton5.getText();
            String g6 = jButton6.getText();
            String g7 = jButton7.getText();
            String g8 = jButton8.getText();
            String g9 = jButton9.getText();

            if (g1.equals(g2) && g2.equals(g3) || g1.equals(g4) && g4.equals(g7) || g1.equals(g5) && g5.equals(g9) || g7.equals(g8) && g8.equals(g9) || g3.equals(g6) && g6.equals(g9) || g4.equals(g5) && g5.equals(g6) || g2.equals(g5) && g5.equals(g8) || g3.equals(g5) && g5.equals(g7)) {
                if (cont % 2 == 0) {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador1 + "'");
                    vict++;
                    String vict1 = Integer.toString(vict);
                    jLabel2.setText(vict1);
                } else {
                    JOptionPane.showMessageDialog(null, ganador + "'" + jugador2 + "'");
                    vict2++;
                    String vict1 = Integer.toString(vict2);
                    jLabel4.setText(vict1);
                }
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
                ver=1;
            }
            if (g1 != b1 && g2 != b2 && g3 != b3 && g4 != b4 && g5 != b5 && g6 != b6 && g7 != b7 && g8 != b8 && g9 != b9) {
                
                if(ver==0)JOptionPane.showMessageDialog(null, empate);
                jButton1.setText(b1);
                jButton2.setText(b2);
                jButton3.setText(b3);
                jButton4.setText(b4);
                jButton5.setText(b5);
                jButton6.setText(b6);
                jButton7.setText(b7);
                jButton8.setText(b8);
                jButton9.setText(b9);
                cont1 = 0;
                cont2 = 0;
                cont3 = 0;
                cont4 = 0;
                cont5 = 0;
                cont6 = 0;
                cont7 = 0;
                cont8 = 0;
                cont9 = 0;
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juego().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
